### ISSUE TITLE
Remove scrolljacking behavior

### ISSUE THREAD

**Issue by TimonLukas** [snakemake/snakemake.github.io#2]
Hello! I stumbled upon this project and it looks quite interesting. However, upon reading the landing page I noticed immediately that the default scroll behavior of my browser wasn't active. The page scrolls much further on each scroll than I am used to. This is not only unintuitive, but also makes reading the examples much harder. With default scroll behavior I can scroll while reading and keep my frame of reference, whereas here it immediately snaps onto the center of the next block, moving the top of the previous block out of the view.

If you implemented this to always align the individual blocks as centered, maybe an alternative would be a "next"/"down arrow" button on the individual blocks? This would keep the behavior without overriding anything.

**Comment by johanneskoester** [comment]
Thanks for reaching out and for the advice! The homepage building was outsourced to some company, and I agree that it was quite messy behind the scenes. However, I have just committed a complete rewrite, which uses just tailwind css.
